name: Integration Tests

on:
  push:
    branches:
      - legacy
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'docker/**'
      - 'nfpm/**'
      - 'private_tangle/**'
      - 'scripts/**'
      - 'tools/**'

jobs:

  common:
    name: common
    env:
      TEST_NAME: common
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build HORNET image
        run: docker build -f docker/Dockerfile.dev -t hornet:dev .

      - name: Pull additional Docker images
        run: |
          docker pull gaiaadm/pumba:0.7.4
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker compose -f integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          sudo chmod 777 integration-tests/logs
          docker logs tester &> integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_NAME }}
          path: integration-tests/logs

  autopeering:
    name: autopeering
    env:
      TEST_NAME: autopeering
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build HORNET image
        run: docker build -f docker/Dockerfile.dev -t hornet:dev .

      - name: Pull additional Docker images
        run: |
          docker pull gaiaadm/pumba:0.7.4
          docker pull gaiadocker/iproute2:latest

      - name: Run integration tests
        run: docker compose -f integration-tests/tester/docker-compose.yml up --abort-on-container-exit --exit-code-from tester --build

      - name: Create logs from tester
        if: always()
        run: |
          sudo chmod 777 integration-tests/logs
          docker logs tester &> integration-tests/logs/tester.log

      - name: Save logs as artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_NAME }}
          path: integration-tests/logs
