name: Release

on:
  release:
    types: [published]

jobs:
  Release:
    name: Release
    runs-on: [ubuntu-latest]
    container:
      image: iotaledger/goreleaser-cgo-cross-compiler:1.20.2
      volumes: [/repo]

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.IOTALEDGER_DOCKER_USERNAME }}
          password: ${{ secrets.IOTALEDGER_DOCKER_PASSWORD }}
      - name: Release HORNET
        run: goreleaser --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
